### ISSUE TITLE
Some images on eclipse.org/research don't show up

### ISSUE THREAD

**Issue by phkrief** [EclipseFdn/eclipse.org-research#61] opened 2021-08-31 22:21 UTC
I noticed before my last changes that some images were not showing up on the eclipse.org/research.
So I tested locally at it seems to work.

Here is what I get locally:
![image](https://user-images.githubusercontent.com/6196602/131583138-1cbd037a-c14f-47cf-9814-9ff4da5dd043.png)
vs what I get on production:
![image](https://user-images.githubusercontent.com/6196602/131583210-31196ddf-ce2c-4999-8a93-55fbb1d14ac6.png)

May I ask you to check it out?

Thx a lot

**Comment by phkrief** [comment] 2021-09-01 07:44
I tried to investigate on my own and I discovered that the staging website doesn't behave the same way.
Actually, I created a new pull request draft and I get this result: https://deploy-preview-62--eclipsefdn-research.netlify.app/
All the images are correctly shown.

HTH

**Comment by phkrief** [comment] 2021-09-01 08:49
Hi @chrisguindon 
May I ask you to check out this issue?
Thx a lot

**Comment by chrisguindon** [comment] 2021-09-01 12:49
The problem is that localhost and netlify preview are hosted in the root but the production website is hosted under /research.

I will look to see if we can mimic production with localhost and netlify.

**Comment by chrisguindon** [comment] 2021-09-02 18:17
The issue should be fixed now! Let me know if you have more issues!

**Closed as completed by chrisguindon** 2021-09-02 18:17 UTC
