### ISSUE TITLE
Some (minor issues) found in the current version

### ISSUE THREAD

**Issue by phkrief** [EclipseFdn/eclipse.org-research#13] opened 2020-04-01 08:54 UTC
Hey @autumnfound ,

The result looks pretty good! Thanks a lot. 
Nevertheless, I notice some minor improvements that you or I could fix.
https://deploy-preview-11--eclipsefdn-research.netlify.com/
Let me share them with you.
- When we mention the H2020 instrument on a project, we should NOT show:

![image](https://user-images.githubusercontent.com/6196602/78116259-50a67980-7404-11ea-9c87-1004aa70600d.png)
but we should show:
![image](https://user-images.githubusercontent.com/6196602/78116314-64ea7680-7404-11ea-97e8-36480bd01e54.png)
instead.

- The social links look too big: We should remove the square around a keep only the button below the logo. So for example for AGILE, we could have:
![image](https://user-images.githubusercontent.com/6196602/78116885-39b45700-7405-11ea-81d4-beb9971a279b.png)

- And I'm not convinced anymore that we must keep the description of the associated Eclipse project(s) because in most of the cases, it will be described in the project description by itself. So I would reduce the size of the right side bar and add the Eclipse projects there. It could look like that:
![image](https://user-images.githubusercontent.com/6196602/78118082-c1e72c00-7406-11ea-8436-daee9b0b54b7.png)

- I also found that the logo of Opees was missing. 
- The Gemoc Studio logo was missing in the project description.

Does it make any sense ?
Thanks a lot for your help
-Philippe

**Comment by phkrief** [comment] 2020-04-01 08:56
Actually, for the size, I will divide by 2 the width of the sidebar. WDYT?

**Comment by autumnfound** [comment] 2020-04-01 13:25
According to the Horizon 2020 [website](https://ec.europa.eu/programmes/horizon2020/en/content/will-horizon-2020-have-logo-andor-visual-identity-which-easy-reproduce), that is the correct mark to use in conjunction with the Horizon 2020 funding.

In terms of moving the social links, the reason it was done this way was to keep it more in line with how it's done within the projects site (e.g. https://projects.eclipse.org/projects/iot.agail). There, the links are separate from the logo branding. We can look at moving those together if you like.

Adding Eclipse projects into the sidebar, I wouldn't recommend that for the same reason that they are in the center content currently. With the potential for multiple projects being associated, multiple funding bodies, the sidebar will be much longer than the main content and make the page look empty. If you'd like to remove the description I can do that.

For opees, the logo is missing from the repository. If we add it and update the path in the opees.md file we should see that update.

The GEMOC studio logo being missing for the EclipseProjects section on the GEMOC page has to do with the actual eclipse project itself (see the [project page here](https://projects.eclipse.org/projects/modeling.gemoc). That needs to be updated by the project team for GEMOC, and can't be fixed on the site.

> Actually, for the size, I will divide by 2 the width of the sidebar. WDYT?

I'm not sure what you're asking for here, could you explain in more detail?

**Comment by phkrief** [comment] 2020-04-01 14:10
- Good point! Then, in this case, we should mention the name of the H2020 program as well and not only the EU flag. WDYT?
![image](https://user-images.githubusercontent.com/6196602/78144561-0fc45a00-7430-11ea-9ca6-976cdb309e64.png)
or
![image](https://user-images.githubusercontent.com/6196602/78144612-1d79df80-7430-11ea-90ef-c65f3b768316.png)

- For the Social Media links, it just looks too big with this huge frame surrounding them with this huge title "Social links". In the projects site (e.g. https://projects.eclipse.org/projects/iot.agail) they look much smaller. Btw, Wayne asked us to avoid looking like an Eclipse project to avoid any confusion. So if we use another format, it should be fine, I guess.

-  I agree with you, if we keep the current sizes and information on the sidebar, it will be too long. Now, if we reduce the sizes of each logos (EU project, Funding, and Eclipse project), if we get rid of the frame and align the social media icon in 1 line, Remove the title "Funded by" to keep only the logo, the sidebar should not be so long.  WDYT?

- I pushed the OPEES logo so it should be there. do you have it? It is difficult to find on the web, FYI.
![image](https://user-images.githubusercontent.com/6196602/78146560-9a0dbd80-7432-11ea-8d81-b16abc385d6d.png)

- I will inform the Gemoc team. thx a lot for this information.

- If you compare an Eclipse Project page with an Eclipse Research project page, the logo on the first one looks smaller than in the second one. So I was suggesting to reduce the size by 30-50% maybe:
![image](https://user-images.githubusercontent.com/6196602/78146991-2d46f300-7433-11ea-9e3f-197f092ae6b0.png)

HTH

**Comment by autumnfound** [comment] 2020-04-01 14:56
I can do something like that for the Horizon image sure! That fits their branding guidelines and is easy enough to do. The social links I can also shrink down a bit as well, it is rather large.

The reason that the sidebar looks different is that the images have less padding and are larger. Otherwise the sidebars are the same width and take up the same page real estate. I can add more padding to make the images smaller to more closely reflect the project's page sidebar if you'd like.

For the sidebar changes, I don't think that removing context and shrinking everything is the answer. Even if we shrink things to half size, with the extra content introduced by stacking eclipse projects in the sidebar would create an unbalanced page. 

Additionally, anyone that comes onto the page that isn't deeply versed in the different funding bodies would have no idea what that section is for or why images are there. This is without getting into lack of accessibility for differently-abled people. I think we should keep the header, and maybe adjust the font size to be a bit smaller.

For now, I'll implement these changes and we can look at how the page looks before we decide on moving the Eclipse projects over to the sidebar.

**Comment by phkrief** [comment] 2020-04-01 15:05
Sounds good compromise, Martin!
Thanks for considering my suggestions.

**Comment by autumnfound** [comment] 2020-04-01 17:29
@ChristieWittEclipse could you create a quick image for the Horizon 2020 logo? We would need an EU flag, with the text 'Horizon 2020' under it. This way we obey the [visual branding guideline](https://ec.europa.eu/programmes/horizon2020/en/content/will-horizon-2020-have-logo-andor-visual-identity-which-easy-reproduce) set by the Horizon 2020 site.

**Comment by ChristieWittEclipse** [comment] 2020-04-02 13:34
@autumnfound I've attached the image, let me know if you need anything else! 
![horizon-2020](https://user-images.githubusercontent.com/58480647/78255280-18b33b00-74c5-11ea-9005-2cf07bc85deb.png)

**Comment by phkrief** [comment] 2020-04-02 13:45
Thx a lot Christie

>
>

**Comment by ChristieWittEclipse** [comment] 2020-04-02 13:45
@phkrief you're welcome!

**Comment by autumnfound** [comment] 2020-04-23 15:06
These changes have all been completed and are live.

**Closed as completed by autumnfound** 2020-04-23 15:06 UTC
